server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mohanreddy592/springcloud-config
          search-paths:
          - 'station*'
#https://github.com/krishnamurthypradeep/springcloud-config

management:
  security:
    enabled: false